name: send email

on:
  workflow_dispatch:
  schedule:
    - cron: "30 02 17 * *"

env:
  SENDER_ADDR: ${{ secrets.SENDER_ADDR_TIM }}
  RECEIVER_ADDR: ${{ secrets.RECEIVER_ADDR_HSING }}
  PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  BANK: "匯豐銀行&國泰世華"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv run python SendEmail.py
