name: send email 2

on:
  schedule:
    - cron: "35 * * * *"

env:
  SENDER_ADDR: ${{ secrets.SENDER_ADDR_TIM }}
  RECEIVER_ADDR: "t109370711@ntut.org.tw"
  PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  BANK: "遠東銀行"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv run python SendEmail.py
