name: send email

on:
  schedule:
    - cron: "* * * * *"

env:
  SENDER_ADDR: secret.SENDER_ADDR_TIM
  RECEIVER_ADDR: "t109370711@ntut.org.tw"
  PASSWORD: secrets.EMAIL_PASSWORD
  BANK: "匯豐銀行&國泰世華"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv run python SendEmail.py
