Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@Jennn-ph 
Jennn-ph
/
automatic_sending
Public
Cannot fork because you own this repository and are not a member of any organizations.
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
Settings
automatic_sending/.github/workflows/email.yml
@Jennn-ph
Jennn-ph Update email.yml
Latest commit 09bfb85 on Aug 21, 2022
History
1 contributor
29 lines (24 sloc)  652 Bytes

name: send email

on:
  schedule:
    - cron: "30 02 17 * *"

env:
  SENDER_ADDR: ${{ secrets.SENDER_ADDR_TIM }}
  RECEIVER_ADDR: ${{ secrets.RECEIVER_ADDR_HSING }}
  PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  BANK: "匯豐銀行&國泰世華"
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and send email
        run: |
          python -m pip install --upgrade pip
          pip install pipenv 
          pipenv install
          pipenv run python SendEmail.py
