name: Scheduled email sending 1

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

jobs:
  scheduled-email-sending:
    uses: ./.github/workflows/send-email.yml
    secrets: inherit
    with:
      bank: "匯豐銀行、國泰世華"
